POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bGFrcGVyZXJhIiwiaWQiOiI2NjU0NGUwMGRlYmViZjdiMTMyNTQ5NjUiLCJpYXQiOjE3MTY4MDg3ODZ9.cpN8TZurN2-pF5zw91ko5Lg5DUDI3cFQUrAW5smRT2w

{
	"title": "bruh v2",
	"author": "Perera",
	"url": "test.com",
	"likes": 3
}