DELETE http://localhost:3003/api/blogs/66546084b9b0ad4b1e1e9f87
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bGFrcGVyZXJhIiwiaWQiOiI2NjU0NGUwMGRlYmViZjdiMTMyNTQ5NjUiLCJpYXQiOjE3MTY4MDg3ODZ9.cpN8TZurN2-pF5zw91ko5Lg5DUDI3cFQUrAW5smRT2w